### ISSUE TITLE
[MYC] Switchable user proxy settings 

### ISSUE THREAD

**Issue by timgassmann** [robcalon/pyetm#6]
It can depend on the working location if additional proxy settings are required or not (e.g. while working in the office or at home). Currently the user has to define in the code how the script connects to the ETM. Therefore a functionality would be nice which recognizes automatically which case is present or - if not possible - add a prompt window when executing the code which allows the user (e.g. via buttons) to select dynamically the way of connection.

**Comment by robcalon** [comment]
User can set proxy settings as environment variable and switch environments for these cases.
